Add caching to tests

diff --git a/tests/scripts/all-committed b/tests/scripts/all-committed
--- a/tests/scripts/all-committed
+++ b/tests/scripts/all-committed
@@ -1,22 +1,39 @@
 #!/usr/bin/env bash
 
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
+function data {
+    locate '/home/chris/Programming/*/.git' |
+    grep -v "/git-html/"
+}
+
+CACHE="results/data/all-committed"
+function cached {
+    if [[ -e "$CACHE" ]] && test $(find "$CACHE" -mmin -60)
+    then
+        cat "$CACHE"
+    else
+        data | tee "$CACHE"
+    fi
+}
+
 function gitClean {
     cd "$1"
-    if git status | grep "nothing to commit, working directory clean" > /dev/null
+    if ! git status | grep "nothing to commit, working directory clean" > /dev/null
     then
         ERR=1
-        COUNT=$((COUNT - 1))
         echo "Uncommited things in '$1'" >> /dev/stderr
+        [[ "$FULL" -eq 1 ]] || exit 1
     fi
 }
 
 ERR=0
-COUNT=10
 while IFS= read -r REPO
 do
     DIR=$(dirname "$REPO")
     gitClean "$DIR"
-    [[ "$COUNT" -eq 0 ]] && break
-done < <(locate '/home/chris/Programming/*/.git')
+done < <(cached)
 
 exit "$ERR"
diff --git a/tests/scripts/cabal-nixable b/tests/scripts/cabal-nixable
--- a/tests/scripts/cabal-nixable
+++ b/tests/scripts/cabal-nixable
@@ -1,14 +1,24 @@
 #!/usr/bin/env bash
 
-ERR=1
-while read -r DIR
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
+ERR=0
+while read -r PROJECT
 do
-    for CABAL in "$DIR"/*.cabal
+    DIR=""
+    for FILE in "$PROJECT"/*.cabal
     do
-        [[ -x "$CABAL" ]]
-        cd "$DIR"
-        hsConfig || { echo "Can't hsConfig in '$DIR'" >> /dev/stderr; ERR=1; }
+        DIR=$(dirname "$FILE")
     done
+    [[ -n "$DIR" ]] || continue
+
+    if ! (cd "$DIR" && hsConfig)
+    then
+        ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
+    fi
 done < <(my_haskell)
 
 exit "$ERR"
diff --git a/tests/scripts/git-repos b/tests/scripts/git-repos
--- a/tests/scripts/git-repos
+++ b/tests/scripts/git-repos
@@ -1,7 +1,23 @@
 #!/usr/bin/env bash
 
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
 function isGit {
     (cd "$1"; git rev-parse --show-toplevel 1> /dev/null 2> /dev/null)
+}
+
+function isSvn {
+    if OUT=$(cd "$1"; svn status --depth=empty 2>&1)
+    then
+        true
+    fi
+    echo "$OUT" | grep "E155036" > /dev/null
+}
+
+function isVC {
+    isGit "$1" || isSvn "$1"
 }
 
 function getDir {
@@ -12,19 +28,46 @@ function getDir {
     done
 }
 
+function skip {
+    FOUND=""
+    while read -r LINE
+    do
+        if ! echo "$FOUND" | grep "$LINE" > /dev/null
+        then
+            FOUND=$(printf '%s\n%s' "$FOUND" "$LINE")
+            echo "$LINE"
+        fi
+    done |
+    grep -v "Programming/CIL" |
+    grep -v "Programming/CCOD"
+}
+
+function data {
+    locate '/home/chris/Programming/*' | getDir | skip
+}
+
+CACHE="results/data/git-repos"
+function cached {
+    mkdir -p results/data
+    if [[ -e "$CACHE" ]] && test $(find "$CACHE" -mmin -60)
+    then
+        cat "$CACHE"
+    else
+        data | tee "$CACHE"
+    fi
+}
+
 # Make sure everything in ~/Programming is version controlled
-COUNT=10 # Stop early if we find this many unversioned things
 ERR=0
 while IFS= read -r DIR
 do
     # Skip if any check passes
-    isGit "$DIR" && continue
+    isVC "$DIR" && continue
 
     # No check passed, so make a note
     echo "$DIR doesn't seem to be version controlled" >> /dev/stderr
     ERR=1
-    COUNT=$(( COUNT - 1 ))
-    [[ "$COUNT" -eq 0 ]] && break
-done < <(locate '/home/chris/Programming/*' | getDir | uniq)
+    [[ "$FULL" -eq 1 ]] || exit 1
+done < <(cached)
 
 exit "$ERR"
diff --git a/tests/scripts/haskell-builds b/tests/scripts/haskell-builds
--- a/tests/scripts/haskell-builds
+++ b/tests/scripts/haskell-builds
@@ -1,5 +1,8 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p bash -i bash
+#!/usr/bin/env bash
+
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
 
 ERR=0
 while IFS= read -r DIR
@@ -9,9 +12,14 @@ do
     then
         echo "Couldn't hsConfig in '$DIR'" >> /dev/stderr
         ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
         continue
     fi
-    cabal build || ERR=1
+    if ! cabal build
+    then
+        ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
+    fi
 done < <(my_haskell)
 
 exit "$ERR"
diff --git a/tests/scripts/hlint b/tests/scripts/hlint
--- a/tests/scripts/hlint
+++ b/tests/scripts/hlint
@@ -1,8 +1,12 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p bash haskellPackages.hlint -i bash
+#!/usr/bin/env bash
+
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
 
 # Run hlint on (almost) everything in ~/Programming/Haskell
 
+CACHE="results/data/hlint"
 function hs {
     my_haskell
     for FILE in ~/Programming/Haskell/*.hs ~/Programming/Haskell/*.lhs
@@ -11,10 +15,24 @@ function hs {
     done
 }
 
+function cached {
+    mkdir -p results/data
+    if [[ -e "$CACHE" ]] && test $(find "$CACHE" -mmin -60)
+    then
+        cat "$CACHE"
+    else
+        hs | tee "$CACHE"
+    fi
+}
+
 ERR=0
 while IFS= read -r HASKELL
 do
-    hlint -XNoCPP "$HASKELL" || ERR=1
-done < <(hs)
+    if ! hlint -XNoCPP "$HASKELL"
+    then
+        ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
+    fi
+done < <(cached)
 
 exit "$ERR"
diff --git a/tests/scripts/hpc-coverage b/tests/scripts/hpc-coverage
--- a/tests/scripts/hpc-coverage
+++ b/tests/scripts/hpc-coverage
@@ -1,5 +1,24 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p bash -p xidel -i bash
+#!/usr/bin/env bash
+
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
+CACHE="results/data/hpc-coverage"
+
+function data {
+    locate -0 "hpc_index.html"
+}
+
+function cached {
+    mkdir -p results/data
+    if [[ -e "$CACHE" && test $(find "$CACHE" -mmin 60) ]]
+    then
+        cat "$CACHE"
+    else
+        data | tee "$CACHE"
+    fi
+}
 
 TOTAL='th[contains(text(),"Program Coverage Total")]'
 PERCENT='following-sibling::td[1]/text()'
@@ -12,7 +31,8 @@ do
     then
         echo "'$RESULT' coverage for '$file'" >> /dev/stderr
         ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
     fi
-done < <(find ~/Programming/Haskell -name "hpc_index.html" -print0)
+done < <(cached)
 
 exit "$ERR"
diff --git a/tests/scripts/no-backups b/tests/scripts/no-backups
--- a/tests/scripts/no-backups
+++ b/tests/scripts/no-backups
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
 function backups {
-    find ~/Programming -name "*~"
-    find ~/Programming -name "#*#"
+    locate -e "/home/chris/Programming/*~"
+    locate -e "/home/chris/Programming/*/#*#"
+    locate -e "/.#"
 }
 
 function skip {
@@ -10,11 +15,11 @@ function skip {
 }
 
 ERR=0
-
 while read -r BACKUP
 do
-    echo "$BACKUP looks like a backup file"
+    echo "$BACKUP looks like a backup file" >> /dev/stderr
     ERR=1
+    [[ "$FULL" -eq 1 ]] || exit 1
 done < <(backups | skip)
 
 exit "$ERR"
diff --git a/tests/scripts/shebangs b/tests/scripts/shebangs
--- a/tests/scripts/shebangs
+++ b/tests/scripts/shebangs
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
+
 ERR=0
 for script in ~/.tests/*.sh ~/.tests/scripts/* ~/warbo-utilities/system/*
 do
@@ -20,6 +24,7 @@ do
         echo "Shebang for $script may not work on NixOS"
         ERR=1
     fi
+    [[ "$ERR" -eq 0 ]] || [[ "$FULL" -eq 1 ]] || exit 1
 done
 
 exit "$ERR"
diff --git a/tests/scripts/shellcheck-tests b/tests/scripts/shellcheck-tests
--- a/tests/scripts/shellcheck-tests
+++ b/tests/scripts/shellcheck-tests
@@ -1,10 +1,15 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p bash -p haskellPackages.ShellCheck -i bash
+#! /usr/bin/env bash
+
+# Pass in the argument "full" to keep going after a failure
+FULL=0
+[[ "x$1" = "xfull" ]] && FULL=1
 
 function skip {
-    # Skip Python and Haskell
+    # Skip Python, Haskell and makefiles
     INPUT=$(grep "^#!")
-    echo "$INPUT" | grep "python" || echo "$INPUT" | grep "haskell"
+    echo "$INPUT" | grep "python"  ||
+    echo "$INPUT" | grep "haskell" ||
+    echo "$INPUT" | grep "gnumake"
 }
 
 shopt -s nullglob
@@ -15,7 +20,11 @@ do
     then
         continue
     fi
-    shellcheck -e SC1008 "$script" || ERR=1
+    if ! shellcheck -e SC1008 -e SC2001 "$script"
+    then
+        ERR=1
+        [[ "$FULL" -eq 1 ]] || exit 1
+    fi
 done
 
 exit "$ERR"
