Don't re-run tests for coverage

diff --git a/tests/scripts/cabal-test b/tests/scripts/cabal-test
--- a/tests/scripts/cabal-test
+++ b/tests/scripts/cabal-test
@@ -19,52 +19,52 @@ function cached {
 
 cached > /dev/null
 
-if CBL=$(./helpers/nthLine.sh "$0" "cabal-test" < <(cached))
+ERR=0
+if NAME=$(./helpers/getName.sh "$0")
 then
-    echo "Testing '$CBL'"
-    DIR=$(dirname "$CBL")
-    FILE=$(basename "$CBL")
-
-    TMP=$(mktemp -d "cabal-test-temp-XXXXX")
-    pushd "$TMP"
-    SUB=$(git clone "$DIR" 2>&1 1> /dev/null |
-          grep "Cloning into"                |
-          sed -e "s/^.*'\([^']*\)'.*$/\1/g")
-
-    pushd "$SUB"
-
-    git remote rm origin
-
-    if ! hsConfig
-    then
-        echo "hsConfig in '$DIR'" >> /dev/stderr
-        exit 1
-    fi
-
-    ERR=0
-    while read -r TEST
+    LINES=$(./helpers/checkNames.sh "$NAME" < <(cached)) || ERR=1
+    while read -r CBL
     do
-        cabal test "$TEST" || {
-            echo "Test suite '$TEST' in '$DIR' failed" >> /dev/stderr
+        echo "Testing '$CBL'"
+        DIR=$(dirname "$CBL")
+        FILE=$(basename "$CBL")
+
+        TMP=$(mktemp -d "cabal-test-temp-XXXXX")
+        pushd "$TMP"
+
+        rsync -rv --exclude=.git "$DIR" .
+        SUB=$(basename "$DIR")
+        pushd "$SUB"
+
+        echo "Running hsConfig in $PWD"
+        if ! hsConfig
+        then
+            echo "hsConfig in '$DIR'" >> /dev/stderr
             ERR=1
-        }
-    done < <(grep "test-suite" < "$FILE" | sed -e 's/^test-suite *\(.*\)$/\1/g')
+        fi
 
-    popd
-    popd
+        [[ "$ERR" -eq 0 ]] && while read -r TEST
+        do
+            cabal test "$TEST" || {
+                echo "Test suite '$TEST' in '$DIR' failed" >> /dev/stderr
+                ERR=1
+            }
+        done < <(grep "test-suite" < "$FILE" | sed -e 's/^test-suite *\(.*\)$/\1/g')
 
-    rm -rf "$TMP"
+        while read -r HPC
+        do
+            echo "Storing coverage report from '$HPC'"
+            mkdir -p ~/Programming/coverage/"$NAME"
+            cp -vr "$HPC" ~/Programming/coverage/"$NAME/"
+        done < <(find . -type d -name html)
 
-    exit "$ERR"
+        popd
+        popd
+        rm -rf "$TMP"
+        [[ "$ERR" -eq 0 ]] || break
+    done < <(echo "$LINES")
 else
-    # No index give, check indices match up
-    CACHECOUNT=$(cached | wc -l)
-    FILECOUNT=$(ls scripts/*.cabal-test | wc -l)
-    if [[ "$CACHECOUNT" -eq "$FILECOUNT" ]]
-    then
-        echo "Got enough tests to cover cabal-test counts"
-    else
-        echo "Have $FILECOUNT test(s) for $CACHECOUNT files" >> /dev/stderr
-        exit 1
-    fi
+    ./helpers/namesMatch.sh "cabal-test" < <(cached) || exit 1
 fi
+
+exit "$ERR"
