Changes

diff --git a/tests/scripts/git-repos b/tests/scripts/git-repos
--- a/tests/scripts/git-repos
+++ b/tests/scripts/git-repos
@@ -4,6 +4,8 @@
 FULL=0
 [[ "x$1" = "xfull" ]] && FULL=1
 
+shopt -s nullglob
+
 function isGit {
     (cd "$1"; git rev-parse --show-toplevel 1> /dev/null 2> /dev/null)
 }
@@ -16,58 +18,88 @@ function isSvn {
     echo "$OUT" | grep "E155036" > /dev/null
 }
 
-function isVC {
-    isGit "$1" || isSvn "$1"
+function isDarcs {
+    (cd "$1"; darcs show files > /dev/null 2> /dev/null)
 }
 
-function getDir {
+function isVC {
+    isGit "$1" || isSvn "$1" || isDarcs "$1"
+}
+
+
+function skip {
+    grep -v "Programming/git-html" |
+    grep -v "\.git"                |
+    grep -v "\.svn"                |
+    grep -v "Programming/CIL"      |
+    grep -v "Programming/CCOD"     |
+    grep -v "Programming/Coq/PACO" |
+    grep -v "Programming/CUDA"     |
+    grep -v "Programming/Djabberd" |
     while read -r LINE
     do
-        [[ -f "$LINE" ]] || continue
-        dirname "$LINE"
+        #if [[ $(( RANDOM % 4 )) -eq 0 ]]
+        #then
+            echo "$LINE"
+        #fi
     done
 }
 
-function skip {
-    FOUND=""
-    while read -r LINE
-    do
-        if ! echo "$FOUND" | grep "$LINE" > /dev/null
-        then
-            FOUND=$(printf '%s\n%s' "$FOUND" "$LINE")
-            echo "$LINE"
-        fi
-    done |
-    grep -v "Programming/CIL" |
-    grep -v "Programming/CCOD"
-}
-
-function data {
-    locate '/home/chris/Programming/*' | getDir | skip
-}
-
-CACHE="results/data/git-repos"
+FAILS="results/data/git-repos"
 function cached {
     mkdir -p results/data
-    if [[ -e "$CACHE" ]] && test $(find "$CACHE" -mmin -60)
+
+    if [[ -e "$FAILS" ]] && test $(find "$FAILS" -mmin -60)
     then
-        cat "$CACHE"
-    else
-        data | tee "$CACHE"
+        cat "$FAILS"
     fi
+
+    # Always include the root
+    echo "/home/chris/Programming"
 }
 
 # Make sure everything in ~/Programming is version controlled
 ERR=0
-while IFS= read -r DIR
-do
-    # Skip if any check passes
-    isVC "$DIR" && continue
 
-    # No check passed, so make a note
-    echo "$DIR doesn't seem to be version controlled" >> /dev/stderr
-    ERR=1
-    [[ "$FULL" -eq 1 ]] || exit 1
-done < <(cached)
+DIRS=$(cached)
+NEW=""
+PREV=""
+while [[ -n "$DIRS" ]]
+do
+    while read -r D
+    do
+        [[ -z "$D" ]] && continue
+        for ENTRY in "$D/"*
+        do
+            [[ -z "$ENTRY" ]] && continue
+            if [[ -d "$ENTRY" ]]
+            then
+                # Skip version-controlled dirs
+                if ! isVC "$ENTRY"
+                then
+                    NEW=$(printf "%s\n%s" "$NEW" "$ENTRY")
+                fi
+            else
+                DN=$(dirname "$ENTRY")
+
+                # Skip any directory we've just seen
+                [[ "x$DN" = "x$PREV" ]] && continue
+                PREV="$DN"
+
+                # Skip if any check passes
+                if ! isVC "$DN"
+                then
+                    # File is not version controlled
+                    echo "$ENTRY doesn't look version controlled" >> /dev/stderr
+                    echo "$DN" >> "$FAILS"
+                    ERR=1
+                    [[ "$FULL" -eq 1 ]] || exit 1
+                fi
+            fi
+        done
+    done < <(echo "$DIRS")
+    DIRS=$(echo "$NEW" | skip)
+    NEW=""
+done
 
 exit "$ERR"
diff --git a/tests/scripts/haskell-builds b/tests/scripts/haskell-builds
--- a/tests/scripts/haskell-builds
+++ b/tests/scripts/haskell-builds
@@ -4,22 +4,49 @@
 FULL=0
 [[ "x$1" = "xfull" ]] && FULL=1
 
+CACHE="results/data/haskell-builds"
+function cached {
+    if [[ -e "$CACHE" ]] && test $(find "$CACHE" -mmin -60)
+    then
+        cat "$CACHE"
+    else
+        my_haskell | tee "$CACHE"
+    fi
+}
+
 ERR=0
 while IFS= read -r DIR
 do
-    cd "$DIR"
-    if ! hsConfig
+    pushd "$DIR"
+    if test -n "$(find . -maxdepth 1 -type f -name '*.cabal' -print -quit)"
     then
-        echo "Couldn't hsConfig in '$DIR'" >> /dev/stderr
-        ERR=1
-        [[ "$FULL" -eq 1 ]] || exit 1
-        continue
+        echo "Found Cabal filein '$DIR', trying to configure and build project"
+        if ! hsConfig
+        then
+            echo "Couldn't hsConfig in '$DIR'" >> /dev/stderr
+            ERR=1
+            [[ "$FULL" -eq 1 ]] || exit 1
+            continue
+        fi
+        if ! cabal build
+        then
+            ERR=1
+            [[ "$FULL" -eq 1 ]] || exit 1
+        fi
+    else
+        echo "No Cabal file in '$DIR', type-checking any individual files"
+        shopt -s nullglob
+        for HS in *.hs *.lhs
+        do
+            echo "Type-checking '$HS'"
+            if ! ghc "$HS" -e 'return ()'
+            then
+                ERR=1
+                [[ "$FULL" -eq 1 ]] || exit 1
+            fi
+        done
     fi
-    if ! cabal build
-    then
-        ERR=1
-        [[ "$FULL" -eq 1 ]] || exit 1
-    fi
-done < <(my_haskell)
+    popd
+done < <(cached)
 
 exit "$ERR"
