Updated tests

diff --git a/tests/scripts/hpc-coverage b/tests/scripts/hpc-coverage
--- a/tests/scripts/hpc-coverage
+++ b/tests/scripts/hpc-coverage
@@ -1,10 +1,17 @@
 #!/usr/bin/env bash
 
+shopt -s nullglob
+
 function data {
+    # Echo out directories containing Cabal files with test-suite entries
     while read -r DIR
     do
-        [[ -d "$DIR/dist" ]] || continue
-        find "$DIR/dist" -name "hpc_index.html"
+        TESTS=0
+        for CBL in "$DIR"/*.cabal
+        do
+            grep "^test-suite" < "$CBL" > /dev/null && TESTS=1
+        done
+        [[ "$TESTS" -eq 1 ]] && echo "$DIR"
     done < <(my_haskell)
 }
 
@@ -12,51 +19,47 @@ function cached {
     ./helpers/cache.sh "hpc-coverage" < <(data)
 }
 
+function reports {
+    find . -name "hpc_index.html"
+}
+
 # Prime the cache
 cached > /dev/null
 
 # Check how we were called
-NAME=$(basename "$0" | cut -c 14-)
-
-ERR=0
-if [[ -z "$NAME" ]]
+if NAME=$(./helpers/getName.sh "$0")
 then
-    echo "No name given, check names match up"
-    while read -r LINE
+    LINES=$(./helpers/checkNames.sh "$NAME" < <(cached)) || ERR=1
+    while read -r DIR
     do
-        GOT=$(./helpers/mkName.sh "$LINE")
-        echo "Looking for test for '$LINE'"
-        FILE="hpc-coverage.$GOT"
-        [[ -e "scripts/$FILE" ]] || {
-            echo "No such file '$FILE', making it"
-            pushd scripts                &&
-            ln -s hpc-coverage "$FILE"   &&
-            popd                         &&
-            touch "results/stdout/$FILE" &&
-            touch "results/stderr/$FILE"
-        } || ERR=1
-    done < <(cached)
-else
-    echo "Checking $NAME" >> /dev/stderr
-    EXIST=0
-    while read -r LINE
-    do
-        FOUND=$(./helpers/mkName.sh "$LINE")
-        [[ "x$FOUND" = "x$NAME" ]] || continue
-        EXIST=1
-        TOTAL='th[contains(text(),"Program Coverage Total")]'
-        PERCENT='following-sibling::td[1]/text()'
-        RESULT=$(xidel - --extract "//${TOTAL}/${PERCENT}" < "$LINE" | tr -d '%')
-        if [[ "$RESULT" -lt "70" ]]
-        then
-            echo "'$RESULT' coverage for '$LINE'" >> /dev/stderr
-            ERR=1
-        fi
-    done < <(cached)
-    [[ "$EXIST" -eq 1 ]] || {
-        echo "Couldn't find coverage report for '$NAME'" >> /dev/stderr
-        ERR=1
-    }
-fi
+        pushd "$DIR"
 
-exit "$ERR"
+        if [[ -z $(reports) ]]
+        then
+            echo "No coverage report found for '$DIR', trying to generate one"
+            { hsConfig && cabal test; } || {
+                echo "Failed to produce coverage for '$DIR'" >> /dev/stderr
+                exit 1
+            }
+        fi
+        # There should definitely be a report now
+        if [[ -z $(reports) ]]
+        then
+            echo "No coverage report generated for '$DIR'" >> /dev/stderr
+            exit 1
+        fi
+        while read -r LINE
+        do
+            TOTAL='th[contains(text(),"Program Coverage Total")]'
+            PERCENT='following-sibling::td[1]/text()'
+            RESULT=$(xidel - --extract "//${TOTAL}/${PERCENT}" < "$LINE" | tr -d '%')
+            if [[ "$RESULT" -lt "70" ]]
+            then
+                echo "'$RESULT' coverage for '$LINE'" >> /dev/stderr
+                exit 1
+            fi
+        done < <(reports)
+    done < <(echo "$LINES")
+else
+    ./helpers/namesMatch.sh "hpc-coverage" < <(cached) || exit 1
+fi
